### ISSUE TITLE
Mysqlnd_ms-master installation issue with PHP 7.1.12 

### ISSUE THREAD

**Issue by Nawazsk89** [sergiotabanelli/mysqlnd_ms#1]
Hi,

Kindly help me to install mysqlnd_ms with PHP 7.1.12. I followed the document which is given in source code folder. And installed all pre-requisite but still facing a below error when trying to run **make**.

mysqlnd_structs.h:134:73: error: invalid type argument of â->â (have âMYSQLND_ERROR_INFOâ)
 #define SET_CLIENT_ERROR(info, err_no, sqlstate, error) (err_no)? (info)->m->set_client_error((info), (err_no), (sqlstate), (error)) : (info)->m->reset((info))

/mysqlnd_ms.c:6277:11: note: in expansion of macro âSET_CLIENT_ERRORâ
           SET_CLIENT_ERROR(*conn->error_info, CR_UNKNOWN_ERROR, UNKNOWN_SQLSTATE, "Error on gtid_set_last_write");

/mysqlnd_structs.h:134:142: error: invalid type argument of â->â (have âMYSQLND_ERROR_INFOâ)
 #define SET_CLIENT_ERROR(info, err_no, sqlstate, error) (err_no)? (info)->m->set_client_error((info), (err_no), (sqlstate), (error)) : (info)->m->reset((info))

mysqlnd_ms.c:6277:11: note: in expansion of macro âSET_CLIENT_ERRORâ
           SET_CLIENT_ERROR(*conn->error_info, CR_UNKNOWN_ERROR, UNKNOWN_SQLSTATE, "Error on gtid_set_last_write");
           ^
make: *** [mysqlnd_ms.lo] Error 1

Regards,
Nawaz

**Comment by sergiotabanelli** [comment]
Glad to hear You. You are my first issue ;). Can You please give some more details about your environment. In example: O.S., do You install PHP from distribution or you compiled from sources, do you have more then one php version? Can You please attach whole output from make (run "make clean" first)

**Comment by sergiotabanelli** [comment]
Maybe I have found problem, committed what  should resolve it. Give it a try, I can test it only tomorrow.

**Comment by sergiotabanelli** [comment]
OK, tested, the issue should has been resolved. Can you please confirm it? While we're at it, can You tell me which kind of MySQL cluster are You using? Single or multi master? Do You use MySQL group replication? Do You plan to use new plugin service level functionalioties like "Server side read consistency" or "Server side write consistency"?(https://github.com/sergiotabanelli/mysqlnd_ms/blob/master/docs/BOOK/QUICKSTART-AND-EXAMPLES/SERVICE-LEVEL-AND-CONSISTENCY.md)

**Comment by Nawazsk89** [comment]
Thank you for your reply, I have successfully installed mysqlnd_ms with your new patch. As per your question we are currently using single master and two slave. Master is use for data write purpose and slave is for data read only.

I am very grateful for all your support.

Regards,
Nawaz
