### ISSUE TITLE
No ini file

### ISSUE THREAD

**Issue by silvanogai** [sergiotabanelli/mysqlnd_ms#11]
My install did not create 
/etc/php.d/50-mysqlnd_ms.ini

I created it manually.

Everything else works fine

Thanks

-- Silvano

**Comment by sergiotabanelli** [comment]
Installing from sources does not provide ini file. Normally Ini files are os distribution dependent, i.e.: ius php extension rpms install ini files with a prepended order number like in your example, remi rpms not.. php o.s. distros have different aproach to extension install...so it is inpratical for sources distribution to guess witch php os distros is installed...i think that also pecl installation does not provide ini files....

**Comment by silvanogai** [comment]
Sergio
thank you for the reply,
I recommend you add this to the documentation
Cheers 

-- Silvano
