### ISSUE TITLE
php 7.2 centos7 apache failure on httpd restart: undefined symbol: mysqlnd_globals

### ISSUE THREAD

**Issue by swansonguitars** [sergiotabanelli/mysqlnd_ms#17]
Sergio,

Thank you for forking and picking up development for mysqlnd_ms!

Issue: mysqlnd_ms fails to load via apache, ok at the command-line.

Successful via the command-line: 
my simple php program attaches to the mysql db as defined in my mysqlnd_ms.json.
A select query returns valid results.

Failure on apache restart:
PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/mysqlnd_ms.so' (tried: /usr/lib64/php/modules/mysqlnd_ms.so (/usr/lib64/php/modules/mysqlnd_ms.so: undefined symbol: mysqlnd_globals)

Tried:
In php.ini, mysqlnd_ms extension is loaded last.  All extensions listed in php.ini exist in /usr/lib64/php/modules

Checked that libraries exist to match ldd 
 ldd mysqlnd_ms.so

Attached in swanson-mysqlnd_ms.tar.gz:
mysqlnd_ms.json.txt - config used for the test 
php_test_results_20200302_1106.txt make test results
php.ini.txt - php config
pdotest.php.txt - my test client program

I appreciate any insight regarding this issue.

Thank you,
Craig Swanson

[swanson-mysqlnd_ms.tar.gz](https://github.com/sergiotabanelli/mysqlnd_ms/files/4276707/swanson-mysqlnd_ms.tar.gz)

**Comment by swansonguitars** [comment]
My environment:
CentOS Linux release 7.7.1908
php 7.2.27-1
mysql-community-common-8.0.19-1

**Comment by sergiotabanelli** [comment]
php 7.2 was installed from ...? remi??  You build mysqlnd_ms against the matching php 7.2 devel package? You have a strange extension_dir in your php.ini, is it OK in php to set extension_dir to an empty string?

**Comment by swansonguitars** [comment]
Sergio,

The issue was with loading the mysqlnd_ms extension properly via apache.
php 72 was installed from the ius repo with matching php-devel.
extension_dir="" is actually okay, but, would be better to define here.

I found that we were using the mpm_event_module on the dev environment (requires zts) but using mpm_prefork_module for the production environment.
Switching back to mpm_prefork_module matched my non-zts build of mysqlnd_ms.

Success!  Thanks again for picking up development of mysqlnd_ms.

Craig
