### ISSUE TITLE
Issues installing on Ubuntu PHP 7x with PHP-FPM

### ISSUE THREAD

**Issue by kronik187** [sergiotabanelli/mysqlnd_ms#19]
I need help in troubleshooting why php-fpm isnt loading the mysqlnd_ms plugin. I am attempting to setup a Ubuntu 18 droplet to RW Master/Slave with DO Managed MySQL.

I have installed dependencies and compiled mysqlnd_ms port based on instruction found here
https://github.com/sergiotabanelli/mysqlnd_ms

I got several errors when running command "make test", here's the log
[php_test_results_20200329_0834.txt](https://github.com/sergiotabanelli/mysqlnd_ms/files/4399477/php_test_results_20200329_0834.txt)
https://pastebin.com/jTGYCf0U

I created the json config file, added these lines to php and then restarted service
extension=mysqlnd_ms.so
mysqlnd_ms.enable=1
mysqlnd_ms.config_file=/etc/mysqlnd_ms_plugin.json

When inspecting phpinfo(), mysqlnm_ms doesnt appear to be loading and test connections returns the "php_network_getaddresses: getaddrinfo failed" error.

Anyone can point out what I did wrong here?

**Comment by sergiotabanelli** [comment]
Tests are not mocked and need 4 effective mysql running instances.. Do you get errors when run php -i? Please post php -i output including stderr. Anyway I will check it next weekend.

**Comment by sergiotabanelli** [comment]
For tests I recently added a docker-compose that could be used to build and run tests for centos 7. 
From your source directory run:
docker-compose -f "docker-compose.yml" up -d --build

then open a a shell on mysqlnd_ms running container, then compile and test, default php is php 5.5, if you want to compile against a different php version use module load and module unload..more or less this way:
```
module load php72
make distclean
phpize
./configure
make
make test
```
Some tests will still fail but those are test bugs not code bugs...

**Comment by kronik187** [comment]
Thanks sergio for taking time to reply to my issue. I’ve made several test and although php72 is my default, it compiled it as in the php74 plugin folder. Once I realized this, I were able to make successful test under the newer version. Now thanks to your docker instructions, I am confident the “module load php72” is the command I was doing wrong.
