### ISSUE TITLE
LIBXML, error when install, mysqlnd_ms

### ISSUE THREAD

**Issue by glagokulan** [sergiotabanelli/mysqlnd_ms#22]
Im getting below error, when i try to install mysqlnd_ms

checking for libmemcached... no
./configure: line 4236: **syntax error near unexpected token `LIBXML,'**
./configure: line 4236: `  PKG_CHECK_MODULES(LIBXML, libxml-2.0 >= 2.7.6)'
$ make
make: *** No targets specified and no makefile found.  Stop.

Please help me to fix this. im using **PHP7.1** and **Ubuntu 18.04**

Thanks in advance

**Comment by sergiotabanelli** [comment]
```
sudo apt-get install libmemcached-dev
sudo apt-get install libxml2-dev
sudo apt-get install php7.1-dev
phpize
./configure
make
sudo make instal
```

**Comment by glagokulan** [comment]
Hi,
I've tried these steps too. Getting the same error. :(

**Comment by sergiotabanelli** [comment]
Sorry, but I don't know Your php env and from where You install php 7.1, but I tested with standard bionic php, that is php 7.2, and works without problem! Check the new dockerfile https://github.com/sergiotabanelli/mysqlnd_ms/blob/master/Dockerfile.bionic
