### ISSUE TITLE
make test failed

### ISSUE THREAD

**Issue by mauriciogior** [sergiotabanelli/mysqlnd_ms#24]
Intro: Hi, we are having issues with max_connections while using php-fpm. We tried using AWS RDS Proxy and it works, however it doesn't support Aurora Serverless yet. We also tried ProxySQL and connecting via unix socket locally. It works well, but on high loads, ProxySQL consumes all our CPU. So we are looking for a way to do connection pooling and it seems that mysqlnd_ms might have that (please correct me if I'm wrong).

Distro: Ubuntu 20.04

```shell
TIME END 2020-08-27 21:14:49

=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   22
---------------------------------------------------------------------

Number of tests :  532                31
Tests skipped   :  501 ( 94.2%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    6 (  1.1%) ( 19.4%)
Tests passed    :   25 (  4.7%) ( 80.6%)
---------------------------------------------------------------------
Time taken      :    7 seconds
=====================================================================

=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
MySQL Fabric: Simple shard lookups (dump) [tests/fabric/fabric_sharding_dump_simple.phpt]
Constants [tests/mysqlnd_ms_constants.phpt]
mysqlnd_ms_dump_servers() [tests/mysqlnd_ms_dump_servers.phpt]
PHP configuration settings [tests/mysqlnd_ms_ini_settings.phpt]
ReflectionExtension basics to check API [tests/mysqlnd_ms_reflection_extension.phpt]
ReflectionFunction to check API [tests/mysqlnd_ms_reflection_functions.phpt]
=====================================================================
```

Do you know what might be the issue with this build? We are using PHP7.4.

Thanks!

**Comment by sergiotabanelli** [comment]
Tests are not mocked, so You need 4 effective mysql instances, see #19 for a description on how to test using docker compose. I don't really understand, in this context, what You mean with `connection pooling`, If You mean `connection multiplexing`, as provided by ProxySQL, sorry but mysqlnd_ms does not have such feature or any other to help reduce the number of connections to the backend.
