### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by louis123562** [sergiotabanelli/mysqlnd_ms#25]
Hello,

i am very new to making / compiling php.

I followed this guide: https://lampcoder.com/58/how-to-setup-mysqln-ms-extension-for-php-7-x

but when i execute the make command, i get this:

<img width="1794" alt="Bildschirmfoto 2021-05-30 um 23 56 07" src="https://user-images.githubusercontent.com/36068395/120121639-d6f35280-c1a4-11eb-9f88-2f7c983dd4f1.png">

I have to say that i already installed php 7.4 fpm via apt - is this the cause?

I thought phpize would recognize it?

Thanks for your help!

**Comment by sergiotabanelli** [comment]
This extension has not been ported to php8 yet

**Comment by ZeroTechnologyLLC** [comment]
@sergiotabanelli please advise of plans for porting extension into php8
thank you

**Comment by sergiotabanelli** [comment]
@ZeroTechnologyLLC Sorry... I missed your comment...But if there are requests and interest by this small comunity, I can probably solve this issue on January... We still do not use php 8 in our environment so this is a low priority task.

**Comment by ZeroTechnologyLLC** [comment]
@sergiotabanelli 
thanks a lot

**Comment by ZeroTechnologyLLC** [comment]
@sergiotabanelli please inform about plans for integration of this feature

Thank you,
Pavel at ZeroTechnology

**Comment by mauriciogior** [comment]
@ZeroTechnologyLLC this is an open source project, it would be great if you could bring this solution in a Pull Request since you are the only one currently needing this solution :)

**Comment by sergiotabanelli** [comment]
I don't have a schedule but Yesterday I start working on it. I hope to close the issue next week... If I'll not find serious technical problems....

**Comment by ZeroTechnologyLLC** [comment]
@sergiotabanelli it's a great news.
Thank you for answer.

**Comment by sergiotabanelli** [comment]
Now it should work also with php 8.0 and php 8.1. Some tests fails, but failures mainly depends from strictness increase in new php versions. Give it a try! I'll still keep open this issue for one or two weeks....

**Comment by louis123562** [comment]
Great to hear that! I will give it a try as soon as i can :)

**Comment by ZeroTechnologyLLC** [comment]
@sergiotabanelli - it's a wonderful news, thank you!
Extension compiled successfully and now we are starting functional testing.
