### ISSUE TITLE
The mysqlnd installed successfully, but the method cannot be used

### ISSUE THREAD

**Issue by 693941639** [sergiotabanelli/mysqlnd_ms#26]
I've installed this extension, but the method still doesn't work.
![1](https://user-images.githubusercontent.com/23370335/143192044-939fef94-aea9-4e70-a87d-e97a3198f324.jpg)
![2](https://user-images.githubusercontent.com/23370335/143192060-5d11b917-2161-4aa2-81b4-6b391e730a15.jpg)
![3](https://user-images.githubusercontent.com/23370335/143192067-10cd78cc-2ab5-4731-8b0f-73c25f59a9a8.jpg)
.

Look forward to your reply, this is on MacOS Monterey Version 12.0.1.

**Comment by sergiotabanelli** [comment]
This is not mysqlnd! This is mysqlnd_ms! Follow the install instruction in the readme.md file
