### ISSUE TITLE
Does this plugin use mysqli_savepoint and named transactions?

### ISSUE THREAD

**Issue by kamil-tekiela** [sergiotabanelli/mysqlnd_ms#27]
The mysqli extension offers two "unfinished" functionalities. My question is whether this plugin is using them or if they could be deprecated. This plugin is the only possible "user" of these functionalities that I can think of. 

1. `mysqli_savepoint()` function. It corresponds to ``SAVEPOINT `foo` `` but doesn't have the corresponding `rollback_to` method.  https://github.com/php/php-src/issues/7818
2. When starting a transaction one can provide it's name via the `$name` parameter. Does your plugin use that value? https://github.com/php/doc-en/issues/1588

**Comment by sergiotabanelli** [comment]
This plugin does not directly call any mysqli entry point. This is a plugin to the mysqlnd extension and use the mysqlnd plugin api not the mysqli api. Mysqli use the mysqnd (mysql native driver) and hence, indirectly, use this plugin if installed.
Sorry for the delayed answer!
