### ISSUE TITLE
PDOException with random characters

### ISSUE THREAD

**Issue by wol-soft** [sergiotabanelli/mysqlnd_ms#28]
Hi,
in very rare cases I experience an exception with an error message triggered by the mysqlnd_ms extension including random characters (looks like unfilled memory data to me). For example (from the PHP error log):

`... PDOException: PDO::__construct(): (mysqlnd_ms) Xè·aÅ^? in ...`

I've had a look into the extension at all places which include the `MYSQLND_MS_ERROR_PREFIX` and found two potential places which set up dynamic error messages:

https://github.com/sergiotabanelli/mysqlnd_ms/blob/master/mysqlnd_ms_switch.c#L478
https://github.com/sergiotabanelli/mysqlnd_ms/blob/master/php_mysqlnd_ms.c#L839

Have you encountered a similar issue during the maintenance of the extension or any hint how to tackle and patch the error?

We haven't yet found the cause so sadly no reproduction steps. The environment is PHP7.4 running on ubuntu 20.04 with the latest version of the mysqlnd_ms extension.

Thanks!

**Comment by sergiotabanelli** [comment]
Sorry for the delayed answer, but You should post your json config at least.
