### ISSUE TITLE
Unable to load dynamic library 'mysqlnd_ms': undefined symbol: mysqlnd_global_stats in Unknown on line 0

### ISSUE THREAD

**Issue by rondey** [sergiotabanelli/mysqlnd_ms#29]
Hello,
I have installed in my server the extension. However, I encounter this error:

`PHP Warning:  PHP Startup: Unable to load dynamic library 'mysqlnd_ms' (tried: /usr/lib/php/20180731/mysqlnd_ms (/usr/lib/php/20180731/mysqlnd_ms: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/mysqlnd_ms.so (/usr/lib/php/20180731/mysqlnd_ms.so: undefined symbol: mysqlnd_global_stats)) in Unknown on line 0`

At the end of the php.ini file I have this:

```
extension=mysqlnd_ms
mysqlnd_ms.enable=1
mysqlnd_ms.config_file=/home/ubuntu/mysqlnd_ms/mysqlnd_ms_plugin.ini
mysqlnd_ms.master_on=INSERT,UPDATE,DELETE,LOAD,REPLACE,CREATE,ALTER,DROP,TRUNCATE,RENAME,LOCK,UNLOCK,CALL
```

This is the content of mysqlnd_ms_plugin.ini:
```
{
    "myapp": {
        "master": {
            "master_0": {
                "host": "MASTER_HOST_IP",
                "port": "PORT"
            }
        },
        "slave": {
            "slave_0": {
                "host": "SLAVE_HOST_IP",
                "port": "PORT"
            }
        }
    }
}
```

Any suggestions? Thank you

**Comment by rondey** [comment]
Problem solved. I will write the steps to solve this issue shortly.

**Comment by sluipmoord** [comment]
> Problem solved. I will write the steps to solve this issue shortly.

Hello @rondey how did you solve the problem? running into similar issues

**Comment by sluipmoord** [comment]
Okay I resolved it by making sure the config loads last
for example, I created the config file for the PHP module here

/etc/php/*/cli/conf.d/26-mysqlnd_md.ini

and running `PHP -m` gives an output of
...
mysqli
mysqlnd
mysqlnd_ms
...

@sergiotabanelli thanks for the fork, going to test this out in development before seeing if makes an impact on our prod servers
