### ISSUE TITLE
Issue on Ubuntu

### ISSUE THREAD

**Issue by clickedu-fxescarmis** [sergiotabanelli/mysqlnd_ms#3]
Hello Mr. Tabanelli,

This new issue references **issue #2** that my colleague @clickedu-inogues sent to you the other day.

These are the steps that we have done:

 1. We have installed your version of the **myslqnd_ms** library in a virtual machine with Ubuntu and PHP7. 
 2. We have configured two different sets of servers: localhost and an active production cluster 
 3. We have tested the library, using our connection class, using the method
    ***get_connection_info()***
 4. We have made the same test in our production application with the library in PHP5

In the joint file [mysqlnd_ms_php7.zip](https://github.com/sergiotabanelli/mysqlnd_ms/files/1818770/mysqlnd_ms_php7.zip) you will find:

 - *vubuntu_phpinfo.html* > The phpinfo() of the virtual server.
 - *mysqlnd.ini* >The mysqlnd configuration file.
 - *mysqlnd_ms_repl_setup.ini* > The mysqlnd_ms configuration file with the two sets of servers.
 - *Connection.php* > The method get_connection_info() of the connection class.
 - *mysqnd_ms_test_results.txt* > The results of the execution.

As you can see with the results, the production cluster with PHP5 returns different hostnames and the value for @role is different, but with PHP7 it does always return the same result.

Could you help us with that, please?

Thanks in advance,

F.X Escarmís
[Clickedu](https://clickartedu.com/)

**Comment by sergiotabanelli** [comment]
OK, I am pretty sure it's a misconfiguration, i have done an ad hoc test in tests/mysqlnd_ms_issue_2.phpt and works for me. You can try it setting right values for "MYSQL_TEST_EMULATED_MASTER_HOST" in tests/config.inc and running "make test TESTS=tests/mysqlnd_ms_issue_2.phpt". The test basically use Your config and code. You should also verify that Your json config is readable by your web server or fast_cgi user. To check set the php ini directive 'mysqlnd_ms.force_config_usage=1', this way You should get errors if json config is not readable. Let me know about it.

**Comment by clickedu-fxescarmis** [comment]
Hello,

I have executed the test. I get this warning message:

> PHP Warning: PHP Startup: Unable to load dynamic library '/root/mysqlnd_ms/modules/mysqlnd_ms.so' - /root/mysqlndms/modules/mysqlnd.so: undefined symbol: mysqlnd_global_stats in Unknown on line 0

Searching about this message, it seems related to the order of the extension loading using php-cli. 
For example, [this link](https://www.linuxquestions.org/questions/slackware-14/php-7-1-in-testing-%BB-unable-to-load-dynamic-library-mysqli-so-4175618544/) says that I have to load **mysqlnd** before **mysqli**. 

I have done some phpdismod and phpenmod. 
In the /etc/php/7.0/cli/conf.d I have the correct order: 10-mysqlnd.ini and 21-mysqli.ini

The warning is still there.

Do you know how can I solve this issue with the module loading?

Many thanks!

**Comment by clickedu-fxescarmis** [comment]
Hello,

I have tried  the steps you have told me and the error persists. 

If you dont' mind, I will wait your test of the extension with the ubuntu 16 image before doing any other step. I hope you find the solution!

Many thanks!

**Comment by sergiotabanelli** [comment]
@clickedu-fxescarmis 
Tested on Ubuntu 16 64 and 32 bit and it works, fixed some compilation warnings and test running bugs. Fixed also a small bug, if the configured json configuration file is absent it now rise an error, maybe this is indirectly related to Your issue. Reset or checkout a new working copy from github and run:

make distclean
phpize
./configure
make test TESTS=tests/mysqlnd_ms_issue_2.phpt

Did You check Your **mysqlnd_ms.config_file** directive and access permission to the configured json file?
Did You try to set the **mysqlnd_ms.force_config_usage=1** ?

**Comment by clickedu-fxescarmis** [comment]
Hello,

I have cloned the latest version of the plugin.
I have done a new config file, which I think is correct. 
I have given the mods_available folder and all its contents 0777 permissions. 
I have set mysqlnd_ms.force_config_usage to 1.

Now I receive this error:

Warning: mysqli::__construct(): (mysqlnd_ms) Exclusive usage of configuration enforced but did not find the correct INI file section (localhost) in /PATH_TO_FILE/Connexio.php on line 989

'localhost' is the first entry of the mysqlnd_ms.ini file.

[v2_config.zip](https://github.com/sergiotabanelli/mysqlnd_ms/files/1859630/v2_config.zip)

I have modified tests/config.inc to configure the localhost connection.
If I do 'make test TESTS=tests/mysqlnd_ms_issue_2.phpt' I receive this:

```

Build complete.
Don't forget to run 'make test'.


=====================================================================
PHP         : /usr/bin/php7.0 
Warning: Unknown: failed to open stream: No such file or directory in Unknown on line 0

Warning: Unknown: (mysqlnd_ms) Failed to open server list config file [/etc/php/7.0/mods_available/mysqlnd_ms.ini] in Unknown on line 0

PHP_SAPI    : cli
PHP_VERSION : 7.0.25-0ubuntu0.16.04.1
ZEND_VERSION: 3.0.0
PHP_OS      : Linux - Linux vubuntu 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64
INI actual  : /root/mysqlnd_ms/tmp-php.ini
More .INIs  :   
CWD         : /root/mysqlnd_ms
Extra dirs  : 
VALGRIND    : Not used
=====================================================================
Running selected tests.
TEST 1/1 [tests/mysqlnd_ms_issue_2.phpt]
SKIP Test for github issue #2 and issue #3 [tests/mysqlnd_ms_issue_2.phpt] reason: (h=localost,u=root,p=,db=test,P=20395,S=), [2000] (mysqlnd_ms) Exclusive usage of configuration enforced but did not find the correct INI file section
=====================================================================
Number of tests :    1                 0
Tests skipped   :    1 (100.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :    0 (  0.0%) (  0.0%)
---------------------------------------------------------------------
Time taken      :    1 seconds
=====================================================================

```

Please, how can I proceed now?

Many thanks,

**Comment by clickedu-fxescarmis** [comment]
Dear Mr. Tabanelli,

Indeed, the problem was a typo in the path of the configuration file as you had discovered! I have corrected the typo, changing the underscore ( _ ) for a hyphen ( - ) in the folder name. Now it works fine.

I feel bad for having fallen in such an amateurish error. Thank you very very much for not giving up with us and finding the solution!

F.X on behalf of the Clickedu team.
