### ISSUE TITLE
Not loaded on Ubuntu

### ISSUE THREAD

**Issue by mrdevdev** [sergiotabanelli/mysqlnd_ms#5]
Hi,

First, thank you for your fork and PHP7 support!

I'm trying to make your extension works in Ubuntu 16 and PHP 7.0

I did all the steps from your installation notes, and it compiled fine.
File /usr/lib/php/20151012/mysqlnd_ms.so created

Here is what I added to php.ini for CLI

```
extension=mysqlnd_ms.so
mysqlnd_ms.enable=1
mysqlnd_ms.force_config_usage=1
mysqlnd_ms.config_file=/etc/php/7.0/mods-available/mysqlnd_ms.ini
```

/etc/php/7.0/mods-available/mysqlnd_ms.ini file exists and contains valid configuration

If I run something, I'm getting the following error:
**PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/mysqlnd_ms.so' - /usr/lib/php/20151012/mysqlnd_ms.so: undefined symbol: mysqlnd_global_stats in Unknown on line 0**
and then none of mysqlnd functions works
**PHP Fatal error:  Uncaught Error: Call to undefined function mysqlnd_ms_dump_servers()**

I tried it with and without mysqlnd_ms.force_config_usage=1

tried to run make test TESTS=tests/mysqlnd_ms_issue_2.phpt and it passed w/o any failures

Can you point me what I'm doing wrong please?

Thanks a lot!

**Comment by sergiotabanelli** [comment]
Did You solve it? It seems an extensions loading order issue, mysqlnd and companion extensions must be loaded before mysqlnd_ms.
