### ISSUE TITLE
Qps drop when one of the slave crash

### ISSUE THREAD

**Issue by huafengchun** [sergiotabanelli/mysqlnd_ms#9]
I tried this plugin, but I always report "No connection selected by last filter", I config 2 slaves, both of them are running. why it report this?

**Comment by huafengchun** [comment]
And I found that when on slave failed, qps will drop to the half or even low. Do you know why it drop ? Thanks!

**Comment by sergiotabanelli** [comment]
Please, post Your json config file and mysqnd_ms ini directives, possibly together with a short code example that reproduce the reported error.

**Comment by sergiotabanelli** [comment]
It seems You are using ZTS (Zend Thread Safe), and the plugin has never been tested with threads! ZTS is one of my next target but still had no time to setup a ZTS development environment and do some tests. 
I don't understand what You mean with <<After change a machine "No connection selected by last filter" error is gone.>> .. Was it a misconfiguration??

For the qps performance drop I took a look at the plugin source code and comparing it to your code and configuration I can only suggest to try set max_retries=0. 
To investigate deeper and if I find a little time I will try to setup a ZTS development enviroment in the next days.

**Comment by huafengchun** [comment]
I don't know why this error gone. I setup a new virtual machine(centos) and try it again, I found no errors at all. May be my old machine has installed too many software and it's hard to tell which one lead to this.

Thanks for your help. I will change max_retries=0 and take more tests.

**Comment by huafengchun** [comment]
Update， One of our customer seems not using a ZTS. But still meet this problem.
Mysqlnd_ms's config file is the same above.
php_config:
configure_options=" '--prefix=/home/git/php' '--with-curl' '--with-freetype-dir' '--with-gd' '--with-gettext' '--with-iconv-dir' '--with-libdir=lib64' '--with-libxml-dir' '--with-mysqli' '--w
ith-openssl' '--with-pear' '--with-png-dir' '--with-zlib' '--with-mcrypt' '--enable-fpm' '--enable-libxml' '--enable-inline-optimization' '--disable-debug' '--enable-gd-native-ttf' '--enable-
mbstring' '--enable-opcache' '--enable-sockets' '--enable-xml' '--enable-zip' '--enable-pdo' '--with-pdo-mysql'"

Can you give me some suggestions? Thanks.

**Comment by sergiotabanelli** [comment]
What do You mean with "slave crash"? I added a test with 2 configured clusters, both with 2 configured slaves, one cluster has a slave with a wrong configured port, that is: connections to that slave will result in a "connection refused" error. There is no relevant performance drop for queries run against the misconfigured cluster (see tests/mysqlnd_ms_issue_9.phpt).

**Comment by huafengchun** [comment]
Two slaves in a cluster, and keep doing some query. Then kill one of the slave, and the QPS drops.

**Comment by sergiotabanelli** [comment]
I can't reproduce it! In my enviroment there is no performance drop! Added a new test with ZTS (50 threads see tests/mysqlnd_ms_zts_issue_9.phpt)  that, in the middle of execution, run a "mysqld stop" on one of the slave, I confirm no qps drop!
 
If with "kill" you mean some action that leave your configured mysql slave port in a state that does not return a "Connection refused" error, but  causes a timeout or a delayed answer then the plugin can't do nothing in that case, expecialy if you destroy and create the mysqli connection on every thread while iteration! That is: the "remember_failed"  configuration option works only on the same connection so if You move the "new mysqli(...)" command ouside the while loop you will get a better qps when a slave node totally stop answers, this way the plugin will know the failure only after a "Connection timeout" error but next queries will not check again the failed slave and queries will directly go to the working slave!
